name: CI/CD to EC2

on:
  push:
    branches: ["test"]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t kevinseya/logistic_websocket_user:latest .

      - name: Push Docker Image
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker push kevinseya/logistic_websocket_user:latest

  deploy-to-ec2:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: SSH into EC2 and deploy container
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
            # Verificar e instalar Docker si es necesario.
            if ! command -v docker &> /dev/null; then
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            # Download the image
            sudo docker pull kevinseya/logistic_websocket_user:latest

            # Stop and remove previous container
            sudo docker stop logistic_websocket_user || true
            sudo docker rm logistic_websocket_user || true

            # Generate .env file
            echo "COUCHDB_URL=${{ secrets.COUCHDB_URL }}" > .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env
            echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
            echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> .env
            echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
            echo "MARIADB_HOST=${{ secrets.MARIADB_HOST }}" >> .env
            echo "MARIADB_USER=${{ secrets.MARIADB_USER }}" >> .env
            echo "MARIADB_PASSWORD=${{ secrets.MARIADB_PASSWORD }}" >> .env
            echo "MARIADB_PORT=${{ secrets.MARIADB_PORT }}" >> .env
            echo "MARIADB_DATABASE=${{ secrets.MARIADB_DATABASE }}" >> .env

            # Run new container
            sudo docker run -d --name logistic_websocket_user \
              --env-file .env \
              -p 3001:3001 \
              kevinseya/logistic_websocket_user:latest
          EOF
